% incomplete LDL'-decomposition for the 2D-poisson problem on a rectangular
% domain with Dirichlet boundary conditions. We assume the stencil
% [ 0 -1  0
%  -1  4 -1
%   0 -1  0]
% to be sufficient. The function should return the same L and D matrices as
% incompleteLDL(A) applied to a matrix A generated by
% generate2DPoisson(x,y).
% x - number of grid points in x-direction (incl. boundary points)
% y - number of grid points in y-direction (incl. boundary points)
function [L,invD] = incompleteLDLPoisson2D(x,y);

% size of actual linear problem
N=x*y;

% init L such that diagonal entries are already correct (i.e. L(i,i)=1)
L = eye(N,N);
% init invD with ones, so that Dirichlet values are already set correctly.
% Since there are no values for Dirichlet conditions in L (on its
% non-diagonal entries) and since invD=1 for these points, we only have to
% work on the inner points in the following.
invD = ones(N,1);


% for inner nodes
for yy = 2 : 1 : y-1
  for xx = 2 : 1 : x-1
    % determine equation for this point (lexicographic ordering)
    i = xx + (yy-1)*x;
    % write out the formulas from incompleteLDL for the lower left entries
    % in A and insert the values of the matrix A (-1 or 4, respectively).
    L(i,i-x) = -1;
    L(i,i-1) = -1 - L(i,i-x)*invD(i-x)*L(i-1,i-x);
    invD(i) = 4 - L(i,i-x)^2*invD(i-x) - L(i,i-1)^2*invD(i-1);
    L(i,i) = invD(i);
    invD(i) = 1/invD(i);
  end
end

return
